<?php declare(strict_types = 1);

/*  Idea (c) 2023 Nikita Zhavoronkov, nikzh@nikzh.com
 *  Copyright (c) 2023-2024 3xpl developers, 3@3xpl.com, see CONTRIBUTORS.md
 *  Distributed under the MIT software license, see LICENSE.md  */

function autogen_test(?array $tests_for_blocks, ?string $module_name) 
{
    $block_test = "";
    $test_block_format = "['block' => %s, 'result' => '%s'],";
    $test_block_transaction_format = "['block' => %s, 'transaction' => '%s', 'result' => '%s'],";
    foreach ($tests_for_blocks as $i => $tests)
    {
        if(isset($tests['transaction']))
            $block_test .= sprintf($test_block_transaction_format, $tests['block'], $tests['transaction'], $tests['events']);
        else
            $block_test .= sprintf($test_block_format, $tests['block'], $tests['result']);
    }
    $tests = "\$tests = [" . $block_test . "];";
    print_in_file($tests, $module_name);
}

function print_in_file(string $array2print, string $module_name) 
{
    if (!file_exists(__DIR__ . "/../Modules/Tests/"))
        mkdir(__DIR__ . "/../Modules/Tests/", 0777);
    $initiator = "<?php \n";
    $header = "\n/*\tIdea (c) 2023 Nikita Zhavoronkov, nikzh@nikzh.com \n*\tCopyright (c) 2023-2024 3xpl developers, 3@3xpl.com, see CONTRIBUTORS.md \n*\tDistributed under the MIT software license, see LICENSE.md  */ \n\n/*\tThis file was autogenerated by AutoGenTest DO NOT TOUCH ANYTHING */ \n\n";

    $class = "class " . $module_name . "Test \n{\n\tpublic static %s \n}\n";
    $final_class = sprintf($class, $array2print);
    $final_class = $initiator . $header . $final_class;
    print(__DIR__ . "/../Modules/Tests/" . $module_name . "Test.php");
    $f = fopen(__DIR__ . "/../Modules/Tests/" . $module_name . "Test.php", 'w');
    fwrite($f, $final_class);
    fclose($f);
}