<?php 

/*	Idea (c) 2023 Nikita Zhavoronkov, nikzh@nikzh.com 
*	Copyright (c) 2023-2024 3xpl developers, 3@3xpl.com, see CONTRIBUTORS.md 
*	Distributed under the MIT software license, see LICENSE.md  */ 

/*	This file was autogenerated by AutoGenTest DO NOT TOUCH ANYTHING */ 

class TronTRC721ModuleTest 
{
	public static $tests = [['block' => 63937672, 'result' => 'a:2:{s:6:"events";a:0:{}s:10:"currencies";a:0:{}}'],['block' => 40521139, 'result' => 'a:2:{s:6:"events";a:2:{i:0;a:8:{s:11:"transaction";s:64:"f89f5a2e6740676a5b1f8d105164f1a134cb1a1d896e7fd682e92deca90aad43";s:8:"currency";s:34:"TWS2dqBEscxGnNKC2jqv9zef38PH4Ea1nb";s:7:"address";s:34:"TDjGZEs9rhwS4zBQV1a57ZdoG7DVceydwD";s:8:"sort_key";i:0;s:6:"effect";s:2:"-1";s:5:"extra";s:4:"7945";s:5:"block";i:40521139;s:4:"time";s:19:"2022-05-09 17:07:51";}i:1;a:8:{s:11:"transaction";s:64:"f89f5a2e6740676a5b1f8d105164f1a134cb1a1d896e7fd682e92deca90aad43";s:8:"currency";s:34:"TWS2dqBEscxGnNKC2jqv9zef38PH4Ea1nb";s:7:"address";s:34:"TPfHBrap4kuzEBSfSLEvAWvkkHMPFYagUD";s:8:"sort_key";i:1;s:6:"effect";s:1:"1";s:5:"extra";s:4:"7945";s:5:"block";i:40521139;s:4:"time";s:19:"2022-05-09 17:07:51";}}s:10:"currencies";a:1:{i:0;a:3:{s:2:"id";s:34:"TWS2dqBEscxGnNKC2jqv9zef38PH4Ea1nb";s:4:"name";s:7:"Ocerest";s:6:"symbol";s:3:"OCR";}}}'],['block' => 8342720, 'result' => 'a:2:{s:6:"events";a:0:{}s:10:"currencies";a:0:{}}'],['block' => 29560345, 'result' => 'a:2:{s:6:"events";a:0:{}s:10:"currencies";a:0:{}}'],]; 
}
